### ISSUE TITLE
Hi, could you tell me the environment requirement?

### ISSUE THREAD

**Issue by hongluzhou** [albertyang33/FOREST#1]
Hi! I'm interested in using your code. Could you tell me the environment requirement, i.e., pyTorch version etc? Thank you very much!!

**Comment by albertyang33** [comment]
Here are all the packages installed in the environment (of course most of them are unnecessary):

# Name                    Version                   Build  Channel
argparse                  1.4.0                     <pip>
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
boto                      2.49.0                    <pip>
boto3                     1.9.91                    <pip>
botocore                  1.12.91                   <pip>
bz2file                   0.98                      <pip>
ca-certificates           2018.03.07                    0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
certifi                   2018.11.29               py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cffi                      1.11.5           py36he75722e_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
chardet                   3.0.4                     <pip>
cuda90                    1.0                  h6433d27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
cudatoolkit               9.2                           0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cycler                    0.10.0                    <pip>
Cython                    0.29.5                    <pip>
decorator                 4.4.1                     <pip>
deepwalk                  1.0.3                     <pip>
docutils                  0.14                      <pip>
futures                   3.1.1                     <pip>
gensim                    3.7.1                     <pip>
idna                      2.8                       <pip>
intel-openmp              2019.1                      144    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
jmespath                  0.9.3                     <pip>
kiwisolver                1.1.0                     <pip>
libedit                   3.1.20170329         h6b74fdf_2    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libgfortran-ng            7.3.0                hdf63c60_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
matplotlib                3.1.2                     <pip>
mido                      1.2.9                     <pip>
mkl                       2019.1                      144    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_fft                   1.0.6            py36hd81dba3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_random                1.0.2            py36hd81dba3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ncurses                   6.1                  he6710b0_1    defaults
networkx                  2.4                       <pip>
ninja                     1.8.2            py36h6bb024c_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy                     1.15.4           py36h7e9f1db_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy-base                1.15.4           py36hde5b4d6_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
openssl                   1.1.1a               h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pip                       18.1                     py36_0    defaults
pretty-midi               0.2.8                     <pip>
psutil                    5.5.0                     <pip>
py-midi                   1.2.5                     <pip>
pycparser                 2.19                     py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pyparsing                 2.4.5                     <pip>
pyserial                  3.4                       <pip>
python                    3.6.7                h0371630_0    defaults
python-dateutil           2.8.0                     <pip>
pytorch                   0.4.0           py36_cuda9.0.176_cudnn7.1.2_1  [cuda90]  https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
readline                  7.0                  h7b6447c_5    defaults
requests                  2.21.0                    <pip>
s3transfer                0.2.0                     <pip>
scikit-learn              0.20.2                    <pip>
scipy                     1.2.1                     <pip>
setuptools                40.6.3                   py36_0    defaults
six                       1.12.0                    <pip>
sklearn                   0.0                       <pip>
smart-open                1.8.0                     <pip>
sqlite                    3.26.0               h7b6447c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
tqdm                      4.28.1           py36h28b3542_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
urllib3                   1.24.1                    <pip>
wheel                     0.32.3                   py36_0    defaults
xz                        5.2.4                h14c3975_4    defaults
zlib                      1.2.11               h7b6447c_3    defaults

**Comment by hongluzhou** [comment]
Thank you so much!!! Just now I sent you another email asking about this,
please ignore that. Thank you so much really!


Regards,
Honglu Zhou
PhD Student, Computer Science Department

Rutgers, the State University of New Jersey

**Comment by hongluzhou** [comment]
Thanks again Cheng Yang! I have no trouble in using FOREST now.  :)

Regards,
Honglu Zhou
PhD Student, Computer Science Department

Rutgers, the State University of New Jersey
