### ISSUE TITLE
关于代码的一个文件报错问题

### ISSUE THREAD

**Issue by jonzhao1123** [albertyang33/FOREST#4]
杨教授您好，在Dataloader.py的
Fline 186, in _load_ne 
 embed_file=open(filename,'r')
会报错FileNotFoundError: [Errno 2] No such file or directory: 'data/twitter/dw64.txt'，请问是因为文件有缺失吗

**Comment by jonzhao1123** [comment]
这种情况是在train.py中的parser.add_argument('-network', type=int, default=1)，将默认default改为了1后发生的

**Comment by yangchengbupt** [comment]
这个是加入network embedding进行辅助的模块，dw64.txt是64维的deepwalk向量，因为文件太大当时没传上来。可以直接置0或者自己训练一个deepwalk的表示

**Comment by jonzhao1123** [comment]
感谢杨教授！祝您生活愉快



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月22日 11:49 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [albertyang33/FOREST] 关于代码的一个文件报错问题 (Issue #4) |

这个是加入network embedding进行辅助的模块，dw64.txt是64维的deepwalk向量，因为文件太大当时没传上来。可以直接置0或者自己训练一个deepwalk的表示

**Comment by yangyui** [comment]
教授您好，就是我发现如果将parser.add_argument('-network', type=int, default=1)，并且自己提取了dw64.txt文件，代码能正常运行，但是结果很差很差

**Comment by yangyui** [comment]
并且 效果变差实在进入RL之后
