### ISSUE TITLE
关于loss的一个问题

### ISSUE THREAD

**Issue by Yewx0310** [albertyang33/FOREST#7]
杨教授您好
我在download您的代码后，运行时候出现了ppl这个值是nan的问题
请问这个是怎么导致的呢？

**Comment by yangchengbupt** [comment]
我印象不影响正常训练。这份代码是基于一个language model的代码改的，所以有个ppl的指标，和information diffusion任务没关系，主要关注loss就可以了

**Comment by Yewx0310** [comment]
This is an automatic reply, confirming that your e-mail was received. Thank you.--------------------------------------------Best WishesWenxue Ye.

**Comment by Yewx0310** [comment]
好的感谢杨教授

**Comment by Yewx0310** [comment]
This is an automatic reply, confirming that your e-mail was received. Thank you.--------------------------------------------Best WishesWenxue Ye.
